language: ruby

cache: bundler

rvm: 2.7.3

script:
  - bundle exec rake test
  - bundle exec danger

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

addons:
  apt:
    packages:
    - libcurl4-openssl-dev # required to avoid SSL errors
